services:
  local_replica:
    image: mysql
    container_name: xdrsync-localreplica
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: xd
    ports:
      - 127.0.0.1:3306:3306
